- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    NUMBER: 70
  tasks:
  - name: print if number is less than 100
    ansible.builtin.debug:
      msg: "number {{ NUMBER }} less than 100"
    when: NUMBER<100
