- name: using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"
  - name: installing nginx on debian
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"

