- name: data types in ansible
  hosts: local
  connection: local
  vars:
    DURATION: "120" #num
    COURSE: DevSecOps # string
    IS_LIVE: true # boolean
    TOOLS: # list
    - linux
    - shell
    - ansible
    CONCEPTS: # map or object or dictionary
      CI: jenkins
      SCRIPT: "shell, ansible, terraform, python"
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration: {{ DURATION }} is-live: {{ IS_LIVE }}, tools: {{ TOOLS }}, concepts: {{ concepts }},"