- name: loops
  hosts: frontend
  become: yes
  tasks:
  - name: loops
    ansible.builtin.package:
      name: "{{ item }}"
      state: "{{ item }}"
    loop:
    - nginx
    - mysql
    - zip



# - name: loops
#   hosts: frontend
#   become: yes
#   tasks:
#   - name: loops
#     ansible.builtin.package:
#       name: "{{ item.name }}"
#       state: "{{ item.state }}
#     loop:
#     - nginx
#     - mysql
#     - zip
